Repository walker-di/walker, pull requests merged in 2025-06, with the labels that each got.

#2 test
  packages/ai-ui-kit/e2e/demo.test.ts
  packages/ai-ui-kit/playwright.config.ts
  packages/ai-ui-kit/src/routes/page.svelte.test.ts
Labels: Review effort 2/5

#4 save test results - playwrite and vitest
  .github/workflows/github-pages.yml
  package-lock.json
  packages/ai-ui-kit/.gitignore
  packages/ai-ui-kit/package-lock.json
  packages/ai-ui-kit/package.json
  packages/ai-ui-kit/playwright.config.ts
  packages/ai-ui-kit/vite.config.ts
  packages/ai-ui-kit/vitest-setup-client.ts
Labels: Review effort 2/5, Possible security concern

#7 wip
  packages/ai-ui-kit/package-lock.json
  packages/ai-ui-kit/package.json
  packages/ai-ui-kit/src/lib/components/canvas-view/README.md
  packages/ai-ui-kit/src/lib/components/canvas-view/canvas-view-model.svelte.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/canvas-view.stories.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/canvas-view.svelte
  packages/ai-ui-kit/src/lib/components/canvas-view/components/canvas-header.svelte
  packages/ai-ui-kit/src/lib/components/canvas-view/components/canvas-sidebar-nav.svelte
  packages/ai-ui-kit/src/lib/components/canvas-view/components/canvas-sidebar.svelte
  packages/ai-ui-kit/src/lib/components/canvas-view/components/canvas-toolbar.svelte
  packages/ai-ui-kit/src/lib/components/canvas-view/index.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/services/canvas-service.svelte.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/services/canvas-zoom-pan.svelte.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/types/canvas.ts
  packages/ai-ui-kit/src/lib/components/canvas-view/utils/canvas-tools.ts
  packages/ai-ui-kit/src/lib/index.ts
  packages/ai-ui-kit/src/routes/+page.svelte
  packages/ai-ui-kit/src/routes/canvas-demo/+page.svelte
Labels: Review effort 4/5, Possible security concern
